#ifndef DATA_STRUCT_ERROR_CODE_H
#define DATA_STRUCT_ERROR_CODE_H

#include <stdio.h>
#include <stdlib.h>

#define OOM_FAIL 1
#define FREE_NULL_POINTER_FAIL (OOM_FAIL+1)
#define OUT_OF_RANGE_FAIL (FREE_NULL_POINTER_FAIL+1)
#define DE_EMPTY_QUEUE_FAIL (OUT_OF_RANGE_FAIL+1)
#define POP_EMPTY_STACK_FAIL (DE_EMPTY_QUEUE_FAIL+1)
#define PUSH_FULL_STACK_FAIL (POP_EMPTY_STACK_FAIL+1)
#define INSERTE_DUPLICATE_VALUE_IN_BST_FAIL (PUSH_FULL_STACK_FAIL+1)

#endif //DATA_STRUCT_ERROR_CODE_H
