#ifndef DATA_STRUCT_ERROR_CODE_H
#define DATA_STRUCT_ERROR_CODE_H

#define OOM_FAIL 1
#define FREE_NULL_POINTER_FAIL 2
#define DE_EMPTY_QUEUE_FAIL 3
#define POP_EMPTY_STACK_FAIL 4
#define PUSH_FULL_STACK_FAIL 5

#endif //DATA_STRUCT_ERROR_CODE_H
