#ifndef DATA_STRUCT_ERROR_CODE_H
#define DATA_STRUCT_ERROR_CODE_H

#include <stdio.h>
#include <stdlib.h>

#define OOM_FAIL 1
#define ASSERT_IMPOSSIBLE (OOM_FAIL + 1)
#define OUT_OF_RANGE_FAIL (ASSERT_IMPOSSIBLE + 1)
#define DE_EMPTY_QUEUE_FAIL (OUT_OF_RANGE_FAIL + 1)
#define POP_EMPTY_STACK_FAIL (DE_EMPTY_QUEUE_FAIL + 1)
#define PUSH_FULL_STACK_FAIL (POP_EMPTY_STACK_FAIL + 1)
#define INSERT_DUPLICATE_VALUE_IN_BST_FAIL (PUSH_FULL_STACK_FAIL + 1)

#endif  // DATA_STRUCT_ERROR_CODE_H
